# Generated by Django 4.0.2 on 2022-02-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed_date',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='created_date',
            new_name='created',
        ),
    ]
