# Generated by Django 4.0.2 on 2022-02-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_todo_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deleted',
        ),
    ]
