# Generated by Django 4.0.2 on 2022-03-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_favorite_user_customuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='word',
            field=models.CharField(max_length=20),
        ),
    ]
