# Generated by Django 4.0.2 on 2022-03-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_favorite_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
